### ISSUE TITLE
IAT Error: FileNotFoundError: images/

### ISSUE THREAD

**Issue by sergiu-burlacu** [qwiglydee/otree-experiments#26]
I downloaded the repo and ran the code in the instructions. 
I tried all IAT versions but always get the same error which stems from:

File iat/Main.html, line 95, in static; const images_url = "{{ static 'images/' }}";

This is strange since there is a folder images in static. 

Removing that line of code allows the app to run. The image stimuli are not visible, of course.

Thanks for the fantastic work!

**Comment by qwiglydee** [comment]
There were some changes in core oTree related to the static files and that trick doesn't work anymore.

You need to replace the line with `const images_url = "/static/images/";`

**Comment by qwiglydee** [comment]
@oTree-org we still have the "/static/images" hard-coded either on front-end (like in IAT) or back-end (in newer generic app).
Is there something more robust in oTree core?

**Comment by oTree-org** [comment]
I think hardcoding is reasonable here.
