### ISSUE TITLE
introduce a delay between trials

### ISSUE THREAD

**Issue by qwiglydee** [qwiglydee/otree-experiments#4]
That delay could serve mainly as anti-bots measure to prevent flooding and DDoS'ing.

However, big delay also limits maximal possible productivity which impacts experiment flow.

**Comment by qwiglydee** [comment]
@oTree-org would it be ok to put "time.sleep(something)" inside live_method?

I assume they are executed in a dedicated thread and `sleep` shouldn't make any problems?

**Comment by oTree-org** [comment]
You shouldn't use time.sleep(); it will block the whole server process.

**Comment by oTree-org** [comment]
I recommend to do any sleeps/delays on the client side.

**Comment by qwiglydee** [comment]
> I recommend to do any sleeps/delays on the client side.

With "dedicated MTurkers" around, I think we shouldn't trust the client side much.

I'm not sure if the delay is really important though.
