### ISSUE TITLE
refactor updating player stats out from game play code

### ISSUE THREAD

**Issue by qwiglydee** [qwiglydee/otree-experiments#5]
An experiment design may include "practice rounds" (or "calibration rounds") with outcome of the game discarded or saved and used somewhere else.

From the paper by Carpenter and Huet-Vaughn:
"""Along with a pilot, it might also make sense to run a baseline treatment with no incentives
just to get a sense for the importance of intrinsic motivation or the general category of experimenter
demand effects."""

The processing of results should be better moved out to `before_next_page` of the game page, so that user can adjust whether to update player stats or do something else.

**Comment by oTree-org** [comment]
I think this should be fairly easy. The person can make a 2-round game. The first round is the practice round. The code can use `if player.round_number == 1` to condition on whether it's a practice round.

If users show interest in having practice rounds, perhaps we could have a code example of this.

**Comment by qwiglydee** [comment]
> If users show interest in having practice rounds, perhaps we could have a code example of this.

I'm going to put an example of very basic "summarizing stats" code in `before_next_page`, similarly to 'stroop' app.
The matter of practice/real/calibration is just removing/replacing such code for a specific page.
